### ISSUE TITLE
Image upload detect text from picture seems to be broken

### ISSUE THREAD

**Issue by ironiridis** [MSPSocial/helpdesk#1]
Per @t54r4n1: the "detect text from picture" link seems to be having a hard time (upload bar fills and empties repeatedly, nothing is returned upon completion)

**Comment by ironiridis** [comment]
I'll take a look at this later today to see if I can reproduce it and see if anything interesting happens in the browser console and/or inside the instance.

**Comment by ironiridis** [comment]
I ended up not being able to reproduce this on Windows and Chrome. Will try with Android/Chrome too.
![a random screenshot of Gentoo Linux run through the Detect text feature](https://user-images.githubusercontent.com/308159/220498878-acbdab51-d8ca-4c09-a7a9-653c4a3f634f.png)

**Comment by ironiridis** [comment]
Likewise, a very awkward but functional detect-text-from-picture working on Android/Chrome.
![screenshot of Detect text from picture working on Android](https://user-images.githubusercontent.com/308159/220499611-00a182a7-b031-4575-91ae-f2f8f477e64e.png)

**Comment by ironiridis** [comment]
@t54r4n1 What OS and browser were you hitting this on? I have a few more combinations I could try but this might narrow it down more quickly for me.

**Comment by t54r4n1** [comment]
sorry, I tried to use the "reply to email" feature but apparently that doesn't actually work? 

original issue was on android/firefox. i can share that windows/firefox works, having just tried it.

**Comment by ironiridis** [comment]
Oh yeah, the reply via email thing can be pretty particular; I believe the "from" on your email needs to match your github-verified email address, and it does some DKIM validation stuff to prevent impersonation. I'll go grab Firefox for Android and see if I can trigger this; I am not sure how to get browser console output though, so that might not be trivial.

**Comment by t54r4n1** [comment]
Pffft. It's working today on android/firefox. I can't duplicate the issue my own self.

**Comment by ironiridis** [comment]
I was just coming back to say I can't seem to break it on android/firefox myself. Sorry 😬 Could have been something broken in firefox briefly?

**Comment by ironiridis** [comment]
For the record, here's it working (well, mostly) for me
![firefox on android detecting text from one of my posts on MSPSocial](https://user-images.githubusercontent.com/308159/220504692-7de40e19-51e0-4e48-9ae9-600dbc6c165a.png)
